{
  "stats": {
    "submitted": 10,
    "finished": 10,
    "running": 0
  },
  "data": [
    {
      "config_id": 1,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 5220.180204,
      "status": 2,
      "starttime": 1750006490.968512,
      "endtime": 1750006491.105331,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/AutoMLAgent.py\", line 320, in smac_train_function\n    return train_fn(cfg=config, dataset=dataset, seed=seed)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 189, in train\n    model = CNN(num_classes, cfg).to(device)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 115, in __init__\n    self.fc1 = nn.Linear(conv_out_size, cfg.get(\"dense_size_1\"))\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/torch/nn/modules/linear.py\", line 106, in __init__\n    torch.empty((out_features, in_features), **factory_kwargs)\nTypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n\n",
        "error": "TypeError('empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n')"
      }
    },
    {
      "config_id": 1,
      "instance": null,
      "seed": 398764591,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 5220.438005,
      "status": 2,
      "starttime": 1750006491.110929,
      "endtime": 1750006491.1911309,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/AutoMLAgent.py\", line 320, in smac_train_function\n    return train_fn(cfg=config, dataset=dataset, seed=seed)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 189, in train\n    model = CNN(num_classes, cfg).to(device)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 115, in __init__\n    self.fc1 = nn.Linear(conv_out_size, cfg.get(\"dense_size_1\"))\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/torch/nn/modules/linear.py\", line 106, in __init__\n    torch.empty((out_features, in_features), **factory_kwargs)\nTypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n\n",
        "error": "TypeError('empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n')"
      }
    },
    {
      "config_id": 2,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": 1.9231791496276855,
      "time": 3.989017963409424,
      "cpu_time": 8.943027999999686,
      "status": 1,
      "starttime": 1750006491.194644,
      "endtime": 1750006495.1848671,
      "additional_info": {}
    },
    {
      "config_id": 2,
      "instance": null,
      "seed": 398764591,
      "budget": null,
      "cost": 1.9708627462387085,
      "time": 3.5998268127441406,
      "cpu_time": 8.12875299999996,
      "status": 1,
      "starttime": 1750006495.188797,
      "endtime": 1750006498.790687,
      "additional_info": {}
    },
    {
      "config_id": 2,
      "instance": null,
      "seed": 924231285,
      "budget": null,
      "cost": 1.9073036909103394,
      "time": 3.882685899734497,
      "cpu_time": 8.694147000000157,
      "status": 1,
      "starttime": 1750006498.792634,
      "endtime": 1750006502.6770601,
      "additional_info": {}
    },
    {
      "config_id": 3,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": 0.1758425235748291,
      "time": 6.914433717727661,
      "cpu_time": 15.698364000000765,
      "status": 1,
      "starttime": 1750006502.9117172,
      "endtime": 1750006509.8275342,
      "additional_info": {}
    },
    {
      "config_id": 3,
      "instance": null,
      "seed": 398764591,
      "budget": null,
      "cost": 0.21378415822982788,
      "time": 7.273977279663086,
      "cpu_time": 16.00904999999966,
      "status": 1,
      "starttime": 1750006509.831158,
      "endtime": 1750006517.108178,
      "additional_info": {}
    },
    {
      "config_id": 3,
      "instance": null,
      "seed": 924231285,
      "budget": null,
      "cost": 0.21622596681118011,
      "time": 4.528249025344849,
      "cpu_time": 10.349954000000253,
      "status": 1,
      "starttime": 1750006517.1111062,
      "endtime": 1750006521.6411352,
      "additional_info": {}
    },
    {
      "config_id": 4,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 5288.939898,
      "status": 2,
      "starttime": 1750006521.644397,
      "endtime": 1750006521.7260642,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/AutoMLAgent.py\", line 320, in smac_train_function\n    return train_fn(cfg=config, dataset=dataset, seed=seed)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 189, in train\n    model = CNN(num_classes, cfg).to(device)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 115, in __init__\n    self.fc1 = nn.Linear(conv_out_size, cfg.get(\"dense_size_1\"))\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/torch/nn/modules/linear.py\", line 106, in __init__\n    torch.empty((out_features, in_features), **factory_kwargs)\nTypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n\n",
        "error": "TypeError('empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n')"
      }
    },
    {
      "config_id": 4,
      "instance": null,
      "seed": 398764591,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 5289.091341,
      "status": 2,
      "starttime": 1750006521.727925,
      "endtime": 1750006521.7807329,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/AutoMLAgent.py\", line 320, in smac_train_function\n    return train_fn(cfg=config, dataset=dataset, seed=seed)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 189, in train\n    model = CNN(num_classes, cfg).to(device)\n  File \"/Users/amirrezaalasti/Desktop/master/semester 2/AutoML-Agent/scripts/generated_codes/generated_train_function.py\", line 115, in __init__\n    self.fc1 = nn.Linear(conv_out_size, cfg.get(\"dense_size_1\"))\n  File \"/opt/anaconda3/envs/SMAC/lib/python3.10/site-packages/torch/nn/modules/linear.py\", line 106, in __init__\n    torch.empty((out_features, in_features), **factory_kwargs)\nTypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\n\n",
        "error": "TypeError('empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:\\n * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)\\n')"
      }
    }
  ],
  "configs": {
    "1": {
      "batch_size": 64,
      "learning_rate": 0.0007272673426,
      "model_type": "cnn",
      "optimizer": "adam",
      "conv_filters_1": 128,
      "kernel_size": 5,
      "num_conv_layers": 2,
      "pooling_type": "max",
      "conv_filters_2": 256
    },
    "2": {
      "batch_size": 256,
      "learning_rate": 1.47347292e-05,
      "model_type": "mlp",
      "optimizer": "sgd",
      "dense_size_1": 512,
      "dense_size_2": 256,
      "dropout_rate": 0.0956712416373,
      "normalization_strategy": "batchnorm",
      "num_dense_layers": 1,
      "sgd_momentum": 0.4827295406722
    },
    "3": {
      "batch_size": 256,
      "learning_rate": 0.0002663652639,
      "model_type": "mlp",
      "optimizer": "adam",
      "dense_size_1": 512,
      "dense_size_2": 512,
      "dropout_rate": 0.4805368105151,
      "normalization_strategy": "none",
      "num_dense_layers": 2
    },
    "4": {
      "batch_size": 32,
      "learning_rate": 0.0001603935992,
      "model_type": "cnn",
      "optimizer": "sgd",
      "conv_filters_1": 64,
      "kernel_size": 5,
      "num_conv_layers": 2,
      "pooling_type": "avg",
      "sgd_momentum": 0.0,
      "conv_filters_2": 128
    }
  },
  "config_origins": {
    "1": "Initial Design: Sobol",
    "2": "Initial Design: Sobol",
    "3": "Acquisition Function Maximizer: Local Search",
    "4": "Acquisition Function Maximizer: Local Search"
  }
}